function [] = makePlots(analyses, paths, saveFigures)
% Loads outputs that were generated by the specified analysis, run by
% calling main.m, and produces and saves figures.

% saves figures by default
if nargin<3
    saveFigures = true;
end

if any(strcmpi(analyses, "analysis01A"))
    % make plots for Lorenz attractor prediction optimization
    plotAnalysis01A(1:10, paths, saveFigures)
    % make plots for Sprott attractor prediction optimizations
    plotAnalysis01A(11:20, paths, saveFigures)
end

end

